# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "84bed87c642abf1020ff2fe5700197a2"
name = "webhook"
application_url = "https://webhook-kappa.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/customer"
  topics = [
  "customer.tags_removed",
  "customers/delete",
  "customer.tags_added"
]
  include_fields = [ "tags", "id", "customerId" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_publications,write_customers,write_markets,write_metaobject_definitions,write_metaobjects,write_payment_customizations,write_products"

[auth]
redirect_urls = [ "https://webhook-kappa.vercel.app/api/auth" ]

[product.metafields.app.demo_info]
type = "single_line_text_field"
name = "Demo Source Info"
description = "Tracks products created by the Shopify app template for development"

  [product.metafields.app.demo_info.access]
  admin = "merchant_read_write"

[shop.metafields.app.store_tags]
type = "json"
name = "Store Tags"

  [shop.metafields.app.store_tags.access]
  admin = "merchant_read"
